version: '3'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  flight-service:
    build: ./flight-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server

  crew-management-service:
    build: ./crew-management-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server

  aircraft-management-service:
    build: ./aircraft-management-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - config-server

  user-management-service:
    build: ./user-management-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - config-server
