global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flight-service'
    static_configs:
      - targets: ['flight-service:8081']

  - job_name: 'crew-management-service'
    static_configs:
      - targets: ['crew-management-service:8082']

  - job_name: 'aircraft-management-service'
    static_configs:
      - targets: ['aircraft-management-service:8083']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8084']

  - job_name: 'user-management-service'
    static_configs:
      - targets: ['user-management-service:8085']
